---
- name: Create AWS EC2 Instance
  hosts: local
  gather_facts: False
  become: yes
  vars_files:
    - keys.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    keypair: keyG
    instance_type: t2.micro
    image: ami-0dd9f0e7df0f0a138
    region: us-east-2
    count: 1
    security_group: launch-wizard-2
    vpc_subnet_id: subnet-ac97d5e0
    
  tasks:
    - name: Make sure that pip3 is installed
      apt:
        name:
          - python3-pip
        state: present
    - name: Make Sure boto,boto3,docker-py are Installed
      pip:
        name:
          - boto
          - boto3
        state: present
    - name: Create Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        wait: yes
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        count: "{{ count }}"
        instance_tags:
          Name: FirstInstans
      register: ec21   #Start Creation of AWS EC2 Server
  
    - name: Create Second Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        wait: yes
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        count: "{{ count }}"
        instance_tags:
          Name: SecondInstans
      register: ec22   #Start Creation of AWS EC2 Server


    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: ec2-1
      loop: "{{ ec21.instances }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: ec2-2
      loop: "{{ ec22.instances }}"


    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec21.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec22.instances }}"

- name: Configure instance(s)
  hosts: ec2-1
  become: True
  gather_facts: True
  tasks:
    - ping:

    - name: Make sure docker is installed
      apt:
        name: 
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: make sure docker-py installed
      become: yes
      pip:
        name: docker-py

    - name: Docker service start
      service:
        name: docker
        state: started
    - name: Docker service enable
      service:
        name: docker
        enabled: yes


    - name: Clone Git Repository
      git:
        repo: https://github.com/MariaMorozov/MyPythonProject.git
        dest: /home/ubuntu/myproject

    - name: Log into DockerHub
      become: yes
      docker_login:
        username: "mariamorozov"
        password: "123Octavian"
        api_version: auto

    - name: Build an image and push to docker hub
      become: yes
      docker_image:
        build:
          path: /home/ubuntu/myproject/docker_api
        name: mariamorozov/myapi1
        tag: v11
       
        repository: mariamorozov/myapi1
        push: yes
        source: build



- name: Deploy the image on Second Instance
  hosts: ec2-2
  become: yes
  gather_facts: True
  tasks:
    - ping:

    - name: Make sure docker is installed
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes 

    - name: make sure docker-py installed
      become: yes
      pip:
        name: docker-py

    - name: Docker service start
      service:
        name: docker
        state: started
     
    - name: Docker service enable
      service:
        name: docker
        enabled: yes

    - name: pull a Docker Image
      become: yes
      docker_image:
        name: mariamorozov/myapi1:v11   
