---
- name: Create AWS EC2 Instance
  hosts: local
  # connection: local
  gather_facts: false
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    keypair: keyG
    instance_type: t2.micro
    image: ami-0dd9f0e7df0f0a138
    region: us-east-2
    count: 1
    security_group: MySecurityGroup
    vpc_subnet_id: subnet-ac97d5e0
    aws_access_key: 
    aws_secret_key: 
  tasks:
    - name: Create Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        wait: yes
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        count: "{{ count }}"
        instance_tags:
          Name: FirstInstans
      register: ec2   #Start Creation of AWS EC2 Server

    - name: add new host
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2-1
      loop: "{{ ec2.instances }}"

      #- name: connecting to first EC2 via SSH
      #wait_for:
      # host: "{{ item.public_dns_name }}"
      # port: 22
      # state: started
      #loop: "{{ ec2.instances }}"
- name: ping on first instance
  hosts: ec2-1
  #gather_facts: false
  #become: yes
  tasks:
    - ping:

            # - name: Make sure docker is installed
            #apt:
            #name: docker.io
            # state: present
            # update_cache: yes
            #- name: Docker service start
            # service:
            # name: docker
            # state: started
